version: "3.9"

networks:
  traefik-proxy:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pubmatcher_legacy
    restart: unless-stopped
    networks:
      - traefik-proxy
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    labels:
      - traefik.enable=true
      - traefik.http.routers.legacy.rule=Host(`pubmatcher.fr`)|| Host(`www.pubmatcher.fr`)
      - traefik.http.routers.legacy.entrypoints=websecure
      - traefik.http.routers.legacy.tls.certresolver=le
      - traefik.http.services.legacy.loadbalancer.server.port=3000
